data = [
    {'name': 'Instagram', 'follower_count': 450, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 280, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Ariana Grande', 'follower_count': 238, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 235, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 226, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 224, 'description': 'Reality TV personality and businesswoman and Self-Made Billionaire', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 217, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 194, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Beyoncé', 'follower_count': 188, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 180, 'description': 'Footballer', 'country': 'Brasil'},
    {'name': 'National Geographic', 'follower_count': 176, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 173, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'follower_count': 171, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 165, 'description': 'Reality TV personality and Model', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 155, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Nicki Minaj', 'follower_count': 147, 'description': 'Musician', 'country': 'Trinidad and Tobago'},
    {'name': 'Nike', 'follower_count': 142, 'description': 'Sportswear multinational', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 140, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 139, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 122, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 117, 'description': 'Reality TV personality', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 116, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 113, 'description': 'Comedian', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 112, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'FC Barcelona', 'follower_count': 111, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Rihanna', 'follower_count': 106, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Demi Lovato', 'follower_count': 104, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': "Victoria's Secret", 'follower_count': 90, 'description': 'Lingerie brand', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 88, 'description': 'Actress and musician', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 86, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Drake', 'follower_count': 85, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Chris Brown', 'follower_count': 83, 'description': 'Musician', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 82, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Vin Diesel', 'follower_count': 81, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 87, 'description': 'Musician', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 107, 'description': 'Footballer', 'country': 'United Kingdom'},
    {'name': 'Billie Eilish', 'follower_count': 79, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Justin Timberlake', 'follower_count': 77, 'description': 'Musician and actor', 'country': 'United States'},
    {'name': 'UEFA Champions League', 'follower_count': 76, 'description': 'Club football competition', 'country': 'Europe'},
    {'name': 'NASA', 'follower_count': 73, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Emma Watson', 'follower_count': 73, 'description': 'Actress', 'country': 'United Kingdom'},
    {'name': 'Shawn Mendes', 'follower_count': 74, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Virat Kohli', 'follower_count': 72, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Gigi Hadid', 'follower_count': 70, 'description': 'Model', 'country': 'United States'},
    {'name': 'Priyanka Chopra Jonas', 'follower_count': 69, 'description': 'Actress and musician', 'country': 'India'},
    {'name': '9GAG', 'follower_count': 68, 'description': 'Social media platform', 'country': 'China'},
    {'name': 'Ronaldinho', 'follower_count': 66, 'description': 'Footballer', 'country': 'Brasil'},
    {'name': 'Maluma', 'follower_count': 65, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Camila Cabello', 'follower_count': 64, 'description': 'Musician', 'country': 'Cuba'},
    {'name': 'NBA', 'follower_count': 61, 'description': 'Club Basketball Competition', 'country': 'United States'}
]

